server:
  port: 8081

spring:
  application:
    name: dubbo-provider

dubbo:
  application:
    name: dubbo-provider
  protocols:
    dubbo:
      name: dubbo
      port: 20880
    triple:
      name: tri
      port: 50051
  registry:
    address: nacos://${NACOS_ADDRESS:127.0.0.1:8848}
